DATOM/urls.py
#Archivo de urls del proyecto(del proyecto no de una app del proyecto)
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


app_name= 'DATOM'

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("scrap/", include("scrap.urls", namespace="scrap")),
    path("down/", include("down.urls", namespace="down")),
    path("produccion/", include("produccion.urls", namespace="produccion")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from .views import CustomLoginView, CustomRegisterView, LogoutView, home_view, aviso_legal_view, explicacion_view

app_name = 'core'


# URLs para las vistas de login y registro
urlpatterns = [
    path('',home_view, name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),  # URL para la vista de login
    path('register/', CustomRegisterView.as_view(), name='register'),  # URL para la vista de registro
    path('logout/', LogoutView.as_view(next_page='core:home'), name='logout'),  # URL para la vista de logout
    path('aviso_legal/',aviso_legal_view, name="aviso"), #URL para la vista de aviso legal
    path('explicacion/', explicacion_view, name='explicacion') #URL para la ista de explicacion
]

scrap/urls.py
from django.urls import path
from . import views

app_name = 'scrap'

urlpatterns = [
    path('', views.scrap_home, name='scrap_home'),  # Ruta para la página principal de Scrap
    path('list/', views.scrap_list, name='scrap_list'),  # Ruta para listar todos los Scraps
    path('detail_form/', views.scrap_detail_form, name='scrap_detail_form'),  # Ruta para el formulario de detalles de Scrap
    path('detail/<int:id>/', views.scrap_detail, name='scrap_detail'),  # Ruta para ver los detalles de un Scrap específico
    path('new/', views.scrap_new, name='scrap_new'),  # Ruta para crear un nuevo Scrap
    path('new_confirm/', views.scrap_new_confirm, name='scrap_new_confirm'),  # Ruta para confirmar el nuevo Scrap
    path('edit_form/', views.scrap_edit_form, name='scrap_edit_form'),  # Ruta para el formulario de edición de Scrap
    path('edit/<int:id>/', views.scrap_edit, name='scrap_edit'),  # Ruta para editar un Scrap específico
    path('delete_form/', views.scrap_delete_form, name='scrap_delete_form'),# Ruta para el formulario de eliminación de Scrap
    path('delete/<int:id>/', views.scrap_delete, name='scrap_delete'),  # Ruta para eliminar un Scrap específico
    path('delete_confirm/<int:id>', views.scrap_delete_confirm, name='scrap_delete_confirm'),  # Ruta para confirmar eliminación de un Scrap
    path('visualizacion/', views.visualitation, name='visualizacion'),  # Ruta para la visualización de Dashboards y Gráficos
   
]

DATOM/templates/_includes/_aviso_legal.html
{% extends "layout_core.html" %}

{% block head_title %}Aviso Legal | DATOM{% endblock %}
{% block description %}Aviso legal de la aplicación DATOM{% endblock %}

{% block page_content %}
<div class="container">
  <h1 class="text-center">Aviso Legal</h1>
  <p>Aquí va el contenido del aviso legal de la aplicación.</p>
  <a href="{% url 'core:home' %}" class="btn btn-link">Volver a inicio</a>
</div>
{% endblock %}

DATOM/templates/_includes/_footer.html
{% load static %} 
<hr>
<footer>
  <p class="text-center">Copyright © 2025 by "Empresa" | <a href="{% url 'core:aviso' %}">Aviso legal</a></p>
  <p class="text-center">Proyecto DJANGO realizado por Daniel Labrador Benito | La importancia de este proyecto ES LA FUNCIONALIDAD no los estilos</p>
  <a href="{% url 'core:home' %}">
    <img style="width: 150px;" src="{% static 'img/core/logo_DATOM2.png' %}" alt="Logotipo de OPMobility">
  </a>
</footer>

DATOM/templates/_includes/_header.html
{% load static %} 
<header>
  <!-- Logo Principal -->
  <a href="{% url 'core:home' %}">
    <img class="logo" src="{% static 'img/core/logo_DATOM2.png' %}" alt="Logotipo de DATOM">
  </a>

  <!-- Menú de navegación -->
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="border: none;">
      <!-- Aquí está el SVG sin borde ni fondo -->
      <img src="{% static 'img/toggle-icon.svg' %}" alt="Toggle icon" style="width: 40px; height: 40px;">
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mt-2 mt-lg-0">
        <li class="nav-item">
          <a href="{% url 'core:home' %}" class="nav-link">Inicio</a>
        </li>

        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <form method="post" action="{% url 'core:logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-link nav-link">Cerrar sesión</button>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'core:login' %}" class="nav-link">Iniciar sesión</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:register' %}" class="nav-link">Registrarse</a>
          </li>
        {% endif %}

        <li class="nav-item">
          <a href="{% url 'scrap:scrap_home' %}" class="nav-link">Scrap</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Down</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Producción</a>
        </li>
      </ul>
    </div>
  </nav>
</header>